services:
  backend:
    build:
        context: .
        dockerfile: ./docker/Dockerfile
    container_name: backend-service
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
        - postgres
    logging:
        driver: json-file
        options:
            max-size: 50m
            max-file: 3
    restart: unless-stopped
    networks:
        - backend
        - keycloak
  ml-service:
    build:
        context: ./ml-service
        dockerfile: Dockerfile
    container_name: ml-service
    env_file: .env
    ports:
      - 8001:8001
    restart: unless-stopped
    volumes:
        - ./logs:/app/logs
        - ./ml-service/app/weights:/app/app/weights
    networks:
        - backend
  bi-service:
    build:
        context: ./bi-service
        dockerfile: Dockerfile
    container_name: bi-service
    env_file: .env
    depends_on:
      - postgres
    ports:
      - 8002:8002
    restart: unless-stopped
    networks:
      - backend
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: pg
    env_file: .env
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks:
      - backend


# NETWORKS
networks:
    backend:
        driver: bridge
    keycloak:
        external: true
        name: key-cloack_keycloak-network

# VOLUMES
volumes:
    postgres_data:
